name: lost
channels:
  - conda-forge
  - defaults
dependencies:
  - adlfs
  - bokeh
  - dask
  - distributed
  - flask==1.1.2
  - flask-cors
  - flask-jwt-extended==3.13.1
  - flask-ldap3-login
  - flask-mail
  - flask-restx
  - flask-sqlalchemy
  - flask-user
  - flask-wtf
  - fsspec
  - imagesize
  - itsdangerous=1.1.0
  - jinja2<3.1.0
  - jupyterlab
  - mysqlclient
  - mysql-common==8.3.0
  - numpy
  - pandas
  - paramiko
  - psycopg2
  - pudb
  - pyarrow
  - pygelf
  - pyjwt=1.7.1
  - pytest
  - python=3.11
  - python-igraph
  - s3fs
  - scikit-image
  - scikit-learn
  - shapely
  - sk-video
  - sphinx
  - sqlalchemy
  - tqdm
  - uwsgi
  - werkzeug=0.16.1
  - pip:
    - lost_ds==1.2.0a1
    - opencv-python

prefix: /opt/conda/envs/lost
