version: '2'
services:
    lost:
      image: l3pcv/lost:${LOST_VERSION}
      container_name: lost
      command: bash /entrypoint.sh
      env_file:
        - .env
      volumes:
        - ${LOST_HOME}:/${LOST_HOME}
      restart: always
      ports:
        - "${LOST_FRONTEND_PORT}:8080"
      environment:
        PYTHONPATH: "/code/backend"
        ENV_NAME: "lost"
        WORKER_NAME: "lost-0"
        PY3_INIT: "source /opt/conda/bin/activate lost"
      links:
        - db-lost
        - rabbitmqlost

    db-lost:
      image: mysql:5.7
      container_name: db-lost
      volumes:
        - ${LOST_HOME}/mysql:/var/lib/mysql
      restart: always
      environment:
        MYSQL_DATABASE: ${LOST_DB_NAME}
        MYSQL_USER: ${LOST_DB_USER}
        MYSQL_PASSWORD: ${LOST_DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${LOST_DB_ROOT_PASSWORD}

    lost-cv:
      image: l3pcv/lost-cv:${LOST_VERSION}
      container_name: lost-cv
      command: bash /entrypoint.sh
      env_file:
        - .env
      volumes:
        - ${LOST_HOME}:/${LOST_HOME}
      restart: always
      environment:
          PYTHONPATH: "/code/backend"
          ENV_NAME: "lost-cv"
          WORKER_NAME: "lost-cv-0"
          PY3_INIT: "source /opt/conda/bin/activate lost-cv"
      links:
        - db-lost
        - rabbitmqlost

    rabbitmqlost:
      image: rabbitmq:3-management
      container_name: rabbitmqlost
      restart: always
      volumes:
        - ${LOST_HOME}/rabbitmq:/var/lib/rabbitmq